language: android
jdk: oraclejdk8
sudo: required
dist: trusty
group: edge

env:
  global:
    - ANDROID_HOME=/usr/local/android-sdk-26.0.1
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
    - BROWSERSTACK_UPLOAD=https://api.browserstack.com/app-automate/upload
    - BENCHMARK_APK="android/app/build/outputs/apk/app-benchmark-debug.apk"

android:
  components:
    - build-tools-23.0.1
    - build-tools-26.0.1
    - android-26
    - android-23
    - tools

before_install:
  # Install node.js
  - nvm install 8
  - node --version
  - export TZ=Canada/Pacific

install:
  # Setup Android dependencies
  - sudo ln -s /usr/local/android-sdk-25.2.3 /usr/local/android-sdk-26.0.1
  # Install the React Native project dependencies
  - npm install -g yarn
  - yarn

script:
  # Run unit tests using Jest
  - yarn jest
