language: android
jdk: oraclejdk8
sudo: required
dist: trusty
group: edge

android:
  components:
    - build-tools-23.0.1
    - build-tools-26.0.1
    - android-26
    - android-23
    - tools

before_install:
  # Install node.js
  - nvm install 8
  - node --version
  - export TZ=America/Los_Angeles

install:
  # Setup Android dependencies
  - sudo ln -s /usr/local/android-sdk-25.2.3 /usr/local/android-sdk-26.0.1
  # Install the React Native project dependencies
  - npm install -g yarn
  - yarn

script:
  # Run unit tests using Jest
  - yarn jest
