name: Android
on:
  push:
    branches:
      - develop
  pull_request:
    # By default, a workflow only runs when a pull_request 's activity type is
    # opened , synchronize , or reopened. Adding ready_for_review here ensures
    # that CI runs when a PR is marked as not a draft, since we skip CI when a
    # PR is draft
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  backend-tests:
    if: github.event.pull_request.draft == false
    name: backend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.17.1"
      - name: Npm Install
        run: |
          npm ci
          cd src/backend
          npm ci
      - name: Backend Tests
        run: |
          cd src/backend
          npm test
  frontend-tests:
    if: github.event.pull_request.draft == false
    name: frontend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.17.1"
      - name: Npm Install
        run: |
          npm ci
      - name: Build translations
        run: |
          npm run build:translations
      - name: Frontend Tests
        run: |
          npm test
