name: Android
on:
  pull_request:
    # By default, a workflow only runs when a pull_request 's activity type is
    # opened , synchronize , or reopened. Adding ready_for_review here ensures
    # that CI runs when a PR is marked as not a draft, since we skip CI when a
    # PR is draft
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  backend-tests:
    if: github.event.pull_request.draft == false
    name: backend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: "12.16.3"
      - name: Npm Install
        run: |
          npm ci
          cd src/backend
          npm ci
      - name: Backend Tests
        run: |
          cd src/backend
          npm test
  e2e-build:
    if: github.event.pull_request.draft == false
    name: e2e build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache npm files
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache Gradle files
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Node
        uses: actions/setup-node@v1
      - name: Use specific Java version for sdkmanager to work
        uses: joschi/setup-jdk@v2
        with:
          java-version: "openjdk8"
          architecture: "x64"
      # Our build will otherwise use NDK 22, which does not work.
      - name: Delete newer NDK version
        run: rm -rf $ANDROID_HOME/ndk/22*
      - name: Install node_modules
        run: |
          mkdir -p nodejs-assets
          npm ci
      - name: Build backend
        run: |
          npm run build:backend
      - name: Build translations
        run: |
          npm run build:translations
      - name: Build for detox
        run: |
          npm run build-detox-android
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: outputs-apk
          path: android/app/build/outputs/apk
  e2e-tests:
    needs: e2e-build
    name: e2e tests
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: outputs-apk
          path: android/app/build/outputs/apk
      - run: ls -R android/app/build/outputs/apk
